// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConfiguration(arg1) {
  return window['go']['main']['App']['AddConfiguration'](arg1);
}

export function GetAvailableTables() {
  return window['go']['main']['App']['GetAvailableTables']();
}

export function GetConfiguration(arg1) {
  return window['go']['main']['App']['GetConfiguration'](arg1);
}

export function GetCurrentConfigurations() {
  return window['go']['main']['App']['GetCurrentConfigurations']();
}

export function GetTableData(arg1, arg2) {
  return window['go']['main']['App']['GetTableData'](arg1, arg2);
}

export function SetActiveConnection(arg1) {
  return window['go']['main']['App']['SetActiveConnection'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UpdateValue(arg1) {
  return window['go']['main']['App']['UpdateValue'](arg1);
}
